<a href="https://colab.research.google.com/github/matthewpecsok/4482_fall_2026/blob/main/tutorial/Python_and_Colab_Demonstration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This is my first real notebook!

## This is one plus one

In [1]:
1+1 # this is one plus one

2

In [2]:
a = 10

## This is five plus five!

In [3]:
5+5 # this is one plus one

# this is a code cell
# this is more comments
# etc
# etc

10

In [4]:
# this is empty for now

In [5]:
result_one_plus_one = 1 + 1
result_one_plus_one
4+4

8

In [6]:
'hello world!'

'hello world!'

In [7]:
hw = 'hello world!'

In [8]:
float_number = 5.55555555

In [9]:
type(5+5.2)

float

In [10]:
a = 5
a = "hello"

In [11]:
a

'hello'

In [12]:
float_number+float_number

11.1111111

In [13]:
hw+hw

'hello world!hello world!'

In [14]:
"hi"+"5"

'hi5'

In [15]:
"5"+"5"

'55'

In [16]:
5+5

10

In [17]:
some_var = "a"
other_var = "b"
another_var = "c"

In [18]:
str_list = ['a','b','c']

In [19]:
num_list = [1,2,3]

In [20]:
str_list[0]

'a'

In [21]:
num_list[0]

1

In [22]:
new_list = str_list+num_list

In [23]:
type(new_list[5])

int

In [24]:
type((1,2,"g"))

tuple

In [25]:
import numpy as np

In [26]:
np.std(num_list)

0.816496580927726

In [27]:
import pandas as pd

In [28]:
my_df = pd.DataFrame({'first_name':['xiao','sumesh','matt'],
              'purchase_amount':[300.00,200.00,100.00]
              })
my_df

  first_name  purchase_amount
0       xiao            300.0
1     sumesh            200.0
2       matt            100.0

In [29]:
my_df.shape

(3, 2)

In [30]:
my_df.purchase_amount.sum()

600.0

In [31]:
my_df['purchase_amount'].sum()

600.0

In [32]:
my_df.sort_values('purchase_amount',ascending=True)

  first_name  purchase_amount
2       matt            100.0
1     sumesh            200.0
0       xiao            300.0

In [37]:
my_df['over_100'] = my_df['purchase_amount'] > 100
my_df

  first_name  purchase_amount  over_100
0       xiao            300.0      True
1     sumesh            200.0      True
2       matt            100.0     False

In [38]:
my_df[my_df['over_100']==True]

  first_name  purchase_amount  over_100
0       xiao            300.0      True
1     sumesh            200.0      True

In [39]:
my_df[my_df['over_100']==False]

  first_name  purchase_amount  over_100
2       matt            100.0     False

In [34]:
my_df = my_df.drop('over_100',axis=1)

In [35]:
my_df

  first_name  purchase_amount
0       xiao            300.0
1     sumesh            200.0
2       matt            100.0