<a href="https://colab.research.google.com/github/matthewpecsok/4482_fall_2026/blob/main/tutorials/simple_holdout_and_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
import pandas as pd

In [2]:
numbers_to_ten = list(range(10,0,-1))
numbers_to_ten

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [3]:
train_test_split(numbers_to_ten,train_size=.8)

[[10, 5, 6, 9, 4, 1, 8, 7], [2, 3]]

In [4]:
train_test_split(numbers_to_ten,train_size=.8)

[[7, 5, 4, 3, 2, 9, 1, 8], [10, 6]]

notice how these numbers don't match the first set of numbers generated in train_test_split for the same list!

setting the random_state will resolve this randomness and give us the same result each time

In [5]:
train_test_split(numbers_to_ten,train_size=.8,random_state=42)

[[5, 10, 3, 8, 1, 6, 7, 4], [2, 9]]

In [6]:
train_test_split(numbers_to_ten,train_size=.8,random_state=42)

[[5, 10, 3, 8, 1, 6, 7, 4], [2, 9]]

In [7]:
train_test_split(numbers_to_ten,train_size=.7,random_state=42)

[[10, 3, 8, 1, 6, 7, 4], [2, 9, 5]]

In [8]:
data = pd.read_csv('https://raw.githubusercontent.com/matthewpecsok/4482_fall_2026/main/data/CD_additional_balanced.csv',nrows=10,usecols=['age','job','y'])

In [9]:
data.head(10)

   age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
2   49    technician  yes
3   41    technician  yes
4   45   blue-collar  yes
5   42   blue-collar  yes
6   39     housemaid  yes
7   28       unknown  yes
8   44      services  yes
9   42    technician  yes

In [10]:
train_X, test_X = train_test_split(data,train_size=.7,random_state=42)

In [11]:
train_X

   age          job    y
0   41  blue-collar  yes
7   28      unknown  yes
2   49   technician  yes
9   42   technician  yes
4   45  blue-collar  yes
3   41   technician  yes
6   39    housemaid  yes

In [12]:
test_X

   age           job    y
8   44      services  yes
1   49  entrepreneur  yes
5   42   blue-collar  yes

In [13]:
kf = KFold(n_splits=3)

for indexes in kf.split(numbers_to_ten):
    print("Split:", indexes)

Split: (array([4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3]))
Split: (array([0, 1, 2, 3, 7, 8, 9]), array([4, 5, 6]))
Split: (array([0, 1, 2, 3, 4, 5, 6]), array([7, 8, 9]))

In [14]:
kf = KFold(n_splits=3)

for indexes in kf.split(data):
    print("\n\nSPLIT")
    print("Train:", data.iloc[indexes[0]])
    print("Test:", data.iloc[indexes[1]])

SPLIT
Train:    age          job    y
4   45  blue-collar  yes
5   42  blue-collar  yes
6   39    housemaid  yes
7   28      unknown  yes
8   44     services  yes
9   42   technician  yes
Test:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
2   49    technician  yes
3   41    technician  yes


SPLIT
Train:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
2   49    technician  yes
3   41    technician  yes
7   28       unknown  yes
8   44      services  yes
9   42    technician  yes
Test:    age          job    y
4   45  blue-collar  yes
5   42  blue-collar  yes
6   39    housemaid  yes


SPLIT
Train:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
2   49    technician  yes
3   41    technician  yes
4   45   blue-collar  yes
5   42   blue-collar  yes
6   39     housemaid  yes
Test:    age         job    y
7   28     unknown  yes
8   44    services  yes
9   42  technician  yes

In [15]:
kf = KFold(n_splits=5)

for indexes in kf.split(data):
    print("\n\nSPLIT")
    print("Train:", data.iloc[indexes[0]])
    print("Test:", data.iloc[indexes[1]])

SPLIT
Train:    age          job    y
2   49   technician  yes
3   41   technician  yes
4   45  blue-collar  yes
5   42  blue-collar  yes
6   39    housemaid  yes
7   28      unknown  yes
8   44     services  yes
9   42   technician  yes
Test:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes


SPLIT
Train:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
4   45   blue-collar  yes
5   42   blue-collar  yes
6   39     housemaid  yes
7   28       unknown  yes
8   44      services  yes
9   42    technician  yes
Test:    age         job    y
2   49  technician  yes
3   41  technician  yes


SPLIT
Train:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
2   49    technician  yes
3   41    technician  yes
6   39     housemaid  yes
7   28       unknown  yes
8   44      services  yes
9   42    technician  yes
Test:    age          job    y
4   45  blue-collar  yes
5   42  blue-collar  yes


SPLIT
Train:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
2   49    technician  yes
3   41    technician  yes
4   45   blue-collar  yes
5   42   blue-collar  yes
8   44      services  yes
9   42    technician  yes
Test:    age        job    y
6   39  housemaid  yes
7   28    unknown  yes


SPLIT
Train:    age           job    y
0   41   blue-collar  yes
1   49  entrepreneur  yes
2   49    technician  yes
3   41    technician  yes
4   45   blue-collar  yes
5   42   blue-collar  yes
6   39     housemaid  yes
7   28       unknown  yes
Test:    age         job    y
8   44    services  yes
9   42  technician  yes

In [16]:
data = pd.read_csv('https://raw.githubusercontent.com/matthewpecsok/4482_fall_2026/main/data/CD_additional_balanced.csv',usecols=['age','job','y'])

In [17]:
data.y.value_counts()

yes    4640
no     4640
Name: y, dtype: int64

In [18]:
y_target = data.pop('y')

In [19]:
y_target = y_target.eq('yes').mul(1)

In [20]:
y_target

0       1
1       1
2       1
3       1
4       1
       ..
9275    0
9276    0
9277    0
9278    0
9279    0
Name: y, Length: 9280, dtype: int64

In [21]:
data_enc = pd.get_dummies(data)

In [22]:
data_enc.head()

,age,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown
0,41,0,1,0,0,0,0,0,0,0,0,0,0
1,49,0,0,1,0,0,0,0,0,0,0,0,0
2,49,0,0,0,0,0,0,0,0,0,1,0,0
3,41,0,0,0,0,0,0,0,0,0,1,0,0
4,45,0,1,0,0,0,0,0,0,0,0,0,0

In [23]:
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier

In [ ]:
scores = cross_validate(
    DecisionTreeClassifier(ccp_alpha=0), data_enc, y_target, cv=4, scoring=['accuracy','recall','precision'],return_train_score=True)
pd.DataFrame(scores)

,fit_time,score_time,test_accuracy,train_accuracy,test_recall,train_recall,test_precision,train_precision
0,0.027561,0.010020,0.483621,0.667241,0.329310,0.628161,0.476309,0.681421
1,0.018212,0.009364,0.546552,0.646839,0.485345,0.637356,0.553045,0.649678
2,0.016422,0.009904,0.588793,0.626580,0.593103,0.600862,0.588034,0.633444
3,0.010876,0.005630,0.612931,0.618247,0.603448,0.552011,0.615114,0.636303