<a href="https://colab.research.google.com/github/matthewpecsok/4482_fall_2026/blob/main/labs/KNN_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import pandas as pd

from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix,\
recall_score, precision_score, f1_score, accuracy_score, make_scorer,\
precision_recall_fscore_support, mean_absolute_error, mean_squared_error

from sklearn.model_selection import train_test_split, cross_validate

from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')
from google.colab import drive
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.dummy import DummyClassifier
from sklearn.neighbors import kneighbors_graph

In [41]:
titanic_cleaned = pd.read_csv('https://raw.githubusercontent.com/matthewpecsok/4482_fall_2026/main/data/titanic_cleaned.csv').drop('Cabin',axis=1)
titanic_cleaned.Pclass = titanic_cleaned.Pclass.astype('object')
titanic_cleaned = titanic_cleaned[['Survived','Age','Sex','Fare']].head(5).copy()
titanic_cleaned_unscaled = titanic_cleaned[['Age','Sex','Fare']].head(5).copy()

titanic_cleaned_unscaled = pd.get_dummies(titanic_cleaned)
scaler = StandardScaler()
scaler.fit(titanic_cleaned_unscaled)

titanic_scaled = scaler.transform(titanic_cleaned_unscaled)
titanic_scaled = pd.DataFrame(titanic_scaled,columns = titanic_cleaned_unscaled.columns).head()

In [42]:
titanic_cleaned_unscaled.head()

   Survived   Age     Fare  Sex_female  Sex_male
0         0  22.0   7.2500           0         1
1         1  38.0  71.2833           1         0
2         1  26.0   7.9250           1         0
3         1  35.0  53.1000           1         0
4         0  35.0   8.0500           0         1

In [43]:
titanic_scaled

   Survived       Age      Fare  Sex_female  Sex_male
0 -1.224745 -1.505166 -0.816141   -1.224745  1.224745
1  0.816497  1.112514  1.530347    0.816497 -0.816497
2  0.816497 -0.850746 -0.791405    0.816497 -0.816497
3  0.816497  0.621699  0.864024    0.816497 -0.816497
4 -1.224745  0.621699 -0.786825   -1.224745  1.224745

In [44]:
A = kneighbors_graph(X=titanic_cleaned_unscaled,n_neighbors=4,mode='distance',p=1,metric='manhattan')
A = A.toarray()
np.round(A,0)

array([[ 0., 83.,  8., 62., 14.],
       [83.,  0., 75., 21., 69.],
       [ 8., 75.,  0., 54., 12.],
       [62., 21., 54.,  0., 48.],
       [14., 69., 12., 48.,  0.]])

In [45]:
A = kneighbors_graph(X=titanic_cleaned_unscaled,n_neighbors=1,mode='connectivity',p=1,metric='manhattan')
A = A.toarray()
np.round(A,0)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [46]:
A = kneighbors_graph(X=titanic_scaled,n_neighbors=4,mode='distance',p=1,metric='manhattan')
A = A.toarray()
np.round(A,0)

array([[ 0., 11.,  7., 10.,  2.],
       [11.,  0.,  4.,  1.,  9.],
       [ 7.,  4.,  0.,  3.,  8.],
       [10.,  1.,  3.,  0.,  8.],
       [ 2.,  9.,  8.,  8.,  0.]])

In [47]:
A = kneighbors_graph(X=titanic_scaled,n_neighbors=1,mode='connectivity',p=1,metric='manhattan')
A = A.toarray()
np.round(A,0)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [48]:
titanic_cleaned

   Survived   Age     Sex     Fare
0         0  22.0    male   7.2500
1         1  38.0  female  71.2833
2         1  26.0  female   7.9250
3         1  35.0  female  53.1000
4         0  35.0    male   8.0500